package capital.clix.los.enums;

public enum LosStatus {

  CIBIL_DONE, STATEMENT_ANALYSIS_INITIATED, STATEMENT_ANALYSIS_COMPLETE, DELPHI_DONE, SME_PERFIOS_DELPHI_COMPLETE, COMMERCIAL_REQUEST_SENT, PB_DELPHI_COMMERCIAL_COMPLETE, GST_COMPLETE, FSA_COMPLETE, FSA_ANALYSIS_INITIATED, PB_UPDATE_COAPPLICANT_CONSUMER_FETCHED
}
